### ISSUE TITLE
 handle all the errors centrally

### ISSUE THREAD

**Issue by ghost** [gadfaria/express-sequelize-boilerplate#50]
It would be better to handle all the errors centrally.
Extend the error class .Create some api specific errors.
Inside  controllers you can  throw those api specific errors.
The catch block will catch  and call the next function with those errors.
The global error handler will handle those errors with a error response.
This reduces the ambiguity in the development when the project grows larger and makes the project structure clean.
I am interested to make those changes.

**Comment by gadfaria** [comment]
hello Muttaqin1,
I am revisiting this boilerplate, which has been on hold for a few years. 
Thank you for your great suggestions, and please feel free to make the changes and submit a pull request. 
Improvements are always welcome.

**Comment by ghost** [comment]
okay, I'm working on it.
